# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/etudiant/Documents/tp1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/etudiant/Documents/tp1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etudiant/Documents/tp1/CMakeFiles /home/etudiant/Documents/tp1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etudiant/Documents/tp1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TP1

# Build rule for target.
TP1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1
.PHONY : TP1

# fast build rule for target.
TP1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/build
.PHONY : TP1/fast

Labyrinthe.o: Labyrinthe.cpp.o
.PHONY : Labyrinthe.o

# target to build an object file
Labyrinthe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Labyrinthe.cpp.o
.PHONY : Labyrinthe.cpp.o

Labyrinthe.i: Labyrinthe.cpp.i
.PHONY : Labyrinthe.i

# target to preprocess a source file
Labyrinthe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Labyrinthe.cpp.i
.PHONY : Labyrinthe.cpp.i

Labyrinthe.s: Labyrinthe.cpp.s
.PHONY : Labyrinthe.s

# target to generate assembly for a file
Labyrinthe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Labyrinthe.cpp.s
.PHONY : Labyrinthe.cpp.s

Piece.o: Piece.cpp.o
.PHONY : Piece.o

# target to build an object file
Piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Piece.cpp.o
.PHONY : Piece.cpp.o

Piece.i: Piece.cpp.i
.PHONY : Piece.i

# target to preprocess a source file
Piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Piece.cpp.i
.PHONY : Piece.cpp.i

Piece.s: Piece.cpp.s
.PHONY : Piece.s

# target to generate assembly for a file
Piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Piece.cpp.s
.PHONY : Piece.cpp.s

Porte.o: Porte.cpp.o
.PHONY : Porte.o

# target to build an object file
Porte.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Porte.cpp.o
.PHONY : Porte.cpp.o

Porte.i: Porte.cpp.i
.PHONY : Porte.i

# target to preprocess a source file
Porte.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Porte.cpp.i
.PHONY : Porte.cpp.i

Porte.s: Porte.cpp.s
.PHONY : Porte.s

# target to generate assembly for a file
Porte.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Porte.cpp.s
.PHONY : Porte.cpp.s

Principal.o: Principal.cpp.o
.PHONY : Principal.o

# target to build an object file
Principal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Principal.cpp.o
.PHONY : Principal.cpp.o

Principal.i: Principal.cpp.i
.PHONY : Principal.i

# target to preprocess a source file
Principal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Principal.cpp.i
.PHONY : Principal.cpp.i

Principal.s: Principal.cpp.s
.PHONY : Principal.s

# target to generate assembly for a file
Principal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TP1.dir/build.make CMakeFiles/TP1.dir/Principal.cpp.s
.PHONY : Principal.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TP1"
	@echo "... Labyrinthe.o"
	@echo "... Labyrinthe.i"
	@echo "... Labyrinthe.s"
	@echo "... Piece.o"
	@echo "... Piece.i"
	@echo "... Piece.s"
	@echo "... Porte.o"
	@echo "... Porte.i"
	@echo "... Porte.s"
	@echo "... Principal.o"
	@echo "... Principal.i"
	@echo "... Principal.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

